
package glwapi


const (
	CO_SUCCESS			= "SUCCESS"
	CO_ERR_NOAUTH			= "NOAUTH"
	CO_ERR_NOTENOUGH		= "NOTENOUGH"
	CO_ERR_ORDERPAID		= "ORDERPAID"
	CO_ERR_ORDERCLOSED		= "ORDERCLOSED"
	CO_ERR_SYSTEMERROR		= "SYSTEMERROR"
	CO_ERR_APPID_NOT_EXIST		= "APPID_NOT_EXIST"
	CO_ERR_APPID_MCHID_NOT_MATCH	= "APPID_MCHID_NOT_MATCH"
	CO_ERR_LACK_PARAM		= "LACK_PARAM"
	CO_ERR_OUT_TRADE_NO_USED	= "OUT_TRADE_NO_USED"
	CO_ERR_SIGNERROR		= "SIGNERROR"
	CO_ERR_XML_FORMAT_ERROR		= "XML_FORMAT_ERROR"
	CO_ERR_REQUIRE_POST_METHOD	= "REQUIRE_POST_METHOD"
	CO_ERR_POST_DATA_EMPTY		= "POST_DATA_EMPTY"
	CO_ERR_NOT_UTF8			= "NOT_UTF8"
)



const (
	// The successful result code of handle payment result notifcation
	PAYMENT_R_SUCCESS		= "SUCCESS"

	// The failed result code of handle payment result notifcation
	PAYMENT_R_FAIL			= "FAIL"
)


const (
	// WeChat payment Address base
	PAYMENT_URL_BASE		= "https://api.mch.weixin.qq.com"


	// WeChat payment create order url
	PAYMENT_URL_CO			= PAYMENT_URL_BASE + "/pay/unifiedorder"

	//WeChat payment query order url
	PAYMENT_URL_QO			= PAYMENT_URL_BASE + "/pay/orderquery"

	//WeChat payment close order url
	PAYMENT_URL_DO			= PAYMENT_URL_BASE + "/pay/closeorder"

	//WeChat payment refund url
	PAYMENT_URL_RR			= PAYMENT_URL_BASE + "/secapi/pay/refund"

	//WeChat payment query refund url
	PAYMENT_URL_QRR			= PAYMENT_URL_BASE + "/pay/refundquery"

	//WeChat payment download bill url
	PAYMENT_URL_DB			= PAYMENT_URL_BASE + "/pay/downloadbill"
)



const (
	QO_RES_SUCCESS		= "SUCCESS"
	QO_RES_ORDER_NOT_EXIST	= "ORDERNOTEXIST"
	QO_RES_UNKNOWN		= "SYSTEMERROR"
)

const (
	DO_RES_SUCCESS			= "SUCCESS"
	DO_RES_ORDERPAID		= "ORDERPAID"
	DO_RES_ORDERCLOSED		= "ORDERCLOSED"
	DO_RES_SIGNERROR		= "SIGNERROR"
	DO_RES_REQUIRE_POST_METHOD	= "REQUIRE_POST_METHOD"
	DO_RES_XML_FORMAT_ERROR		= "XML_FORMAT_ERROR"
	DO_RES_UNKNOWN			= "SYSTEMERROR"
)

const (
	TRADE_STATE_SUCCESS	= "SUCCESS"
	TRADE_STATE_REFUND	= "REFUND"
	TRADE_STATE_NOT_PAY	= "NOTPAY"
	TRADE_STATE_CLOSED	= "CLOSED"
	TRADE_STATE_REVOKED	= "REVOKED"
	TRADE_STATE_USER_PAYING	= "USERPAYING"
	TRADE_STATE_PAYERROR	= "PAYERROR"
)


const (
	RR_RES_SUCCESS			= "SUCCESS"
	RR_RES_SYSTEMERROR 		= "SYSTEMERROR"
	RR_RES_BIZERR_NEED_RETRY 	= "BIZERR_NEED_RETRY"
	RR_RES_TRADE_OVERDUE 		= "TRADE_OVERDUE"
	RR_RES_ERROR 			= "ERROR"
	RR_RES_USER_ACCOUNT_ABNORMAL 	= "USER_ACCOUNT_ABNORMAL"
	RR_RES_INVALID_REQ_TOO_MUCH 	= "INVALID_REQ_TOO_MUCH"
	RR_RES_NOTENOUGH	 	= "NOTENOUGH"
	RR_RES_INVALID_TRANSACTIONID	= "INVALID_TRANSACTIONID"
	RR_RES_PARAM_ERROR	 	= "PARAM_ERROR"
	RR_RES_APPID_NOT_EXIST	 	= "APPID_NOT_EXISTAPPID"
	RR_RES_MCHID_NOT_EXIST	 	= "MCHID_NOT_EXISTMCHID"
	RR_RES_REQUIRE_POST_METHOD	= "REQUIRE_POST_METHOD"
	RR_RES_SIGNERROR	 	= "SIGNERROR"
	RR_RES_XML_FORMAT_ERROR	 	= "XML_FORMAT_ERROR"
	RR_RES_FREQUENCY_LIMITED 	= "FREQUENCY_LIMITED"
)
